"""empty message

Revision ID: 605d5c71a0b1
Revises: 547b79fdd087
Create Date: 2022-06-12 22:40:32.958274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '605d5c71a0b1'
down_revision = '547b79fdd087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('Venue', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'date_created')
    op.drop_column('Artist', 'date_created')
    # ### end Alembic commands ###
