"""empty message

Revision ID: ee1331c75ea8
Revises: 5b46d4cbfdb0
Create Date: 2022-06-10 08:32:36.567056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee1331c75ea8'
down_revision = '5b46d4cbfdb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('start_time', sa.String(length=50), nullable=False))
    op.drop_column('Shows', 'show_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('show_time', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('Shows', 'start_time')
    # ### end Alembic commands ###
